language: node_js
node_js:
- node
cache: npm
env:
  VUE_APP_BASE_URL: http://api.galleti.io
script: cd web & npm i & npm run build --production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
